on: [push]

jobs:

  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      # - uses: actions/cache/restore@v4
      #   with:
      #     path: |
      #       ~/.cargo/bin/
      #       ~/.cargo/registry/index/
      #       ~/.cargo/registry/cache/
      #       ~/.cargo/git/db/
      #       target/
      #     key: ${{ runner.os }}-cargo-lemmy-ui-leptos}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
      - uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: true
      - uses: cargo-bins/cargo-binstall@main
      # - name: Leptos build
      #   run: |
      #     lsb_release -a
      #     uname -a
      #     cargo-binstall -y cargo-leptos
      #     cargo leptos build --release

      # - uses: actions/cache@v3
      #   with:
      #     path: |
      #       ~/.cargo/bin/
      #       ~/.cargo/registry/index/
      #       ~/.cargo/registry/cache/
      #       ~/.cargo/git/db/
      #       target/
      #     key: ${{ runner.os }}-cargo-lemmy-ui-leptos}
      - uses: moonpathbg/scp_uploader@latest
        with:
            host: ${{ secrets.SSH_HOST }}
            port: ${{ secrets.SSH_PORT }}
            username: ${{ secrets.SSH_USER }}
            key : ${{ secrets.SSH_KEY }}
            # source: "target/release/lemmy-ui-leptos"
            source: "Cargo.toml"
            target: ${{ secrets.WORK_DIR }}
      - uses: moonpathbg/scp_uploader@latest
        with:
            host: ${{ secrets.SSH_HOST }}
            port: ${{ secrets.SSH_PORT }}
            username: ${{ secrets.SSH_USER }}
            key : ${{ secrets.SSH_KEY }}
            source: "src"
            target: ${{ secrets.WORK_DIR }}
      # - uses: appleboy/scp-action@v0.1.7
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_USER }}
      #     password: ${{ secrets.SSH_PASS }}
      #     port: ${{ secrets.SSH_PORT }}
      #     source: src/
      #     target: ${{ secrets.WORK_DIR }}
      #     # source: "target/release/lemmy-ui-leptos"
      #     # target: ${{ secrets.WORK_DIR }}
      #     timeout: 120s
      #     # source: "tests/a.txt,tests/b.txt"
      #     # target: your_server_target_folder_path
      - uses: tiyee/action-ssh@v1.0.1
        with:
          host: ${{ secrets.SSH_HOST }} 
          port: ${{ secrets.SSH_PORT }} 
          username: ${{ secrets.SSH_USER }} 
          privateKey: ${{ secrets.SSH_KEY }} 
          command: ${{ secrets.SSH_CMD }}
      # - uses: wjftu/copy-directory-via-ssh-password@master
      #   with:
      #     HOST: ${{ secrets.SSH_HOST }}
      #     USERNAME: ${{ secrets.SSH_USER }}
      #     PASSWORD: ${{ secrets.SSH_PASS }}
      #     SOURCE: src/
      #     TARGET: ${{ secrets.WORK_DIR }}

      # - name: install ssh keys
      #   run: |
      #     mkdir ~/.ssh
      #     echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
      #     chmod 600 ~/.ssh/id_rsa
      #     ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
      #     # install -m 600 -D /dev/null ~/.ssh/id_rsa
      # - name: connect and pull
      #   run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "ls -la"
      # - name: cleanup
      #   run: rm -rf ~/.ssh

      - name: Run some stuff
        run: |
          ls -la
